name: timecop
description: Simple private time tracking.
version: 1.6.0+36

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.2.5
  sqflite: ^1.2.0
  intl:
  font_awesome_flutter: ^8.7.0
  random_color: ^1.0.3
  flutter_slidable: ^0.5.4
  about: ^1.4.0
  url_launcher: ^5.7.10
  flutter_svg: ^0.19.1
  flutter_material_color_picker: ^1.0.5
  flutter_datetime_picker: ^1.4.0
  csv: ^4.1.0
  path_provider: ^1.6.1
  share: '>=0.6.5+4 <2.0.0'
  shared_preferences: ^0.5.7+3
  fluent: 1.0.2+3
  fl_chart: ^0.12.2
  flutter_swiper: ^1.1.6
  flutter_typeahead: ^1.8.0
  flutter_app_badger: ^1.1.2
  numberpicker: ^1.3.0
  file_picker: ^2.1.4
  flutter_local_notifications: ^3.0.2
  flutter_markdown: ^0.5.2

dev_dependencies:
  pedantic: ^1.0.0
  effective_dart: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  #until screenshots updates on the package repo..
  #screenshots: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "icon_android_fg.png"

flutter:
  uses-material-design: true
  assets:
    - README.md
    - CHANGELOG.md
    - CONTRIBUTORS.md
    - icon.no-bg.svg
    - icon.no-bg.cyan.svg
    - fonts/LICENSE-FiraMono.txt
    - fonts/LICENSE-PublicSans.md
    - l10n/
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Regular.ttf
          weight: 400
