name: timecop
description: Simple private time tracking.
version: 1.6.0+32

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  sqflite: ^1.2.0
  intl:
  font_awesome_flutter: ^8.7.0
  random_color: ^1.0.3
  flutter_slidable: ^0.5.4
  about: ^1.0.5
  url_launcher: ^5.4.2
  flutter_svg: ^0.17.4
  flutter_material_color_picker: ^1.0.5
  flutter_datetime_picker: ^1.3.8
  csv: ^4.0.3
  flutter_share: ^1.0.2+1
  path_provider: ^1.6.1
  shared_preferences: ^0.5.7+3
  fluent: ^1.0.1+2
  fl_chart: ^0.8.3
  flutter_swiper: ^1.1.6
  flutter_typeahead: ^1.8.0

dev_dependencies:
  pedantic: ^1.0.0
  effective_dart: ^1.0.0
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  screenshots: ^2.1.1
  test: ^1.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "icon_android_fg.png"

flutter:
  uses-material-design: true
  assets:
    - README.md
    - CHANGELOG.md
    - CONTRIBUTORS.md
    - icon.no-bg.svg
    - icon.no-bg.cyan.svg
    - fonts/LICENSE-FiraMono.txt
    - fonts/LICENSE-PublicSans.md
    - l10n/
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Regular.ttf
          weight: 400
