name: timecop
description: Simple private time tracking.
version: 1.8.1+45
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite_common_ffi:
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  path: ^1.8.2
  collection: ^1.17.2
  sqflite: ^2.0.2
  intl: ^0.18.0
  font_awesome_flutter: ^10.6.0
  random_color: ^1.0.6-nullsafety
  flutter_slidable: ^3.0.1
  about: ^2.1.3
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  flutter_material_color_picker: ^1.1.0+2
  flutter_datetime_picker_plus: ^2.1.0
  csv: ^5.1.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  cross_file: ^0.3.3
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  card_swiper: ^3.0.1
  flutter_typeahead: ^4.8.0
  flutter_app_badger: ^1.3.0
  numberpicker: ^2.1.1
  file_picker: ^6.1.1
  flutter_local_notifications: ^15.1.0
  flutter_markdown: ^0.6.18
  package_info_plus: ^5.0.1
  xdg_directories: ^1.0.3
  fluent: ^2.0.1
  permission_handler: ^11.0.0
  dynamic_color: ^1.6.8
  pdf: ^3.10.6

dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_driver:
    sdk: flutter
  test: ^1.24.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  #until screenshots updates on the package repo..
  #screenshots: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "icon_android_fg.png"

flutter:
  uses-material-design: true
  assets:
    - README.md
    - CHANGELOG.md
    - CONTRIBUTORS.md
    - icon.no-bg.svg
    - icon.no-bg.cyan.svg
    - fonts/LICENSE-PublicSans.md
    - fonts/OFL-PublicSans.txt
    - l10n/
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Regular.ttf
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
